module.exports = {
  apps: [
    {
      name: "next-app",
      script: "./server.mjs",
      node_args: "--expose-gc --max-old-space-size=2048",
      exec_mode: "cluster",
      instances: "max",
      max_memory_restart: "2G",
      min_uptime: "10s",
      max_restarts: 10,
      autorestart: true,
      watch: false,
      error_file: "./logs/next-app-error.log",
      out_file: "./logs/next-app-out.log",
      merge_logs: true,
      time: true,
      kill_timeout: 5000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        WATCHDOG_CPU_LIMIT: 90,
        WATCHDOG_MEM_LIMIT_MB: 1536,
      },
    },
    {
      name: "pm2-watchdog",
      script: "./src/app/lib/monitor/pm2-watchdog.mjs",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      watch: false,
      error_file: "./logs/watchdog-error.log",
      out_file: "./logs/watchdog-out.log",
      merge_logs: true,
      time: true,
      env: {
        WATCHDOG_POLL_SECONDS: 15,
        WATCHDOG_CPU_LIMIT: 85,
        WATCHDOG_MEM_LIMIT_MB: 1024,
        WATCHDOG_COOLDOWN_SECONDS: 60,
        WATCHDOG_MAX_INTERVENTIONS: 5,
        WATCHDOG_INTERVENTION_WINDOW: 300000,
        WATCHDOG_EXCLUDE: "pm2-watchdog,next-app",
        WATCHDOG_LOG_DIR: "./logs",
        WATCHDOG_LOG_FILE: "pm2-watchdog.log",
      },
    },
  ],
};
